#!/usr/bin/env bash
# Sync repo .md and progress.txt into knowledge/sentinel-docs for Sentinel RAG.
# Run from repo root: ./scripts/sync-sentinel-docs.sh

set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/knowledge/sentinel-docs"
mkdir -p "$OUT"

# Root .md
for f in README.md CLAUDE.md FEATURE-STORE.md DEPLOY.md TREASURY.md ONNX.md BANKR.md X-RESEARCH.md LOCALSONLY.md; do
  [ -f "$ROOT/$f" ] && cp "$ROOT/$f" "$OUT/" || true
done

# docs/
[ -d "$ROOT/docs" ] && cp "$ROOT/docs"/*.md "$OUT/" 2>/dev/null || true

# Plugin READMEs and key docs (flatten with prefix so names are unique)
[ -f "$ROOT/src/plugins/plugin-vince/README.md" ] && cp "$ROOT/src/plugins/plugin-vince/README.md" "$OUT/plugin-vince-README.md" || true
[ -f "$ROOT/src/plugins/plugin-vince/START.md" ] && cp "$ROOT/src/plugins/plugin-vince/START.md" "$OUT/plugin-vince-START.md" || true
[ -f "$ROOT/src/plugins/plugin-vince/WHAT.md" ] && cp "$ROOT/src/plugins/plugin-vince/WHAT.md" "$OUT/plugin-vince-WHAT.md" || true
[ -f "$ROOT/src/plugins/plugin-kelly/README.md" ] && cp "$ROOT/src/plugins/plugin-kelly/README.md" "$OUT/plugin-kelly-README.md" || true
[ -f "$ROOT/src/frontend/docs/README.md" ] && cp "$ROOT/src/frontend/docs/README.md" "$OUT/frontend-docs-README.md" || true

# Consolidated progress: concatenate the three progress.txt with clear headers
{
  echo "# Consolidated progress (plugin-vince, plugin-kelly, frontend)"
  echo ""
  echo "Generated by scripts/sync-sentinel-docs.sh. Source files:"
  echo "- src/plugins/plugin-vince/progress.txt"
  echo "- src/plugins/plugin-kelly/progress.txt"
  echo "- src/frontend/progress.txt"
  echo ""
  echo "---"
  echo ""
  echo "## plugin-vince/progress.txt"
  echo ""
  [ -f "$ROOT/src/plugins/plugin-vince/progress.txt" ] && cat "$ROOT/src/plugins/plugin-vince/progress.txt" || echo "(missing)"
  echo ""
  echo "---"
  echo ""
  echo "## plugin-kelly/progress.txt"
  echo ""
  [ -f "$ROOT/src/plugins/plugin-kelly/progress.txt" ] && cat "$ROOT/src/plugins/plugin-kelly/progress.txt" || echo "(missing)"
  echo ""
  echo "---"
  echo ""
  echo "## frontend/progress.txt"
  echo ""
  [ -f "$ROOT/src/frontend/progress.txt" ] && cat "$ROOT/src/frontend/progress.txt" || echo "(missing)"
} > "$OUT/PROGRESS-CONSOLIDATED.md"

# Rewrite relative links so they resolve when read from knowledge/sentinel-docs/
# Order: ../knowledge/ before ../src/ to avoid rewriting paths inside knowledge
for f in "$OUT"/*.md; do
  [ -f "$f" ] || continue
  sed -e 's|](../README\.md)|](../../README.md)|g' \
      -e 's|](../CLAUDE\.md)|](../../CLAUDE.md)|g' \
      -e 's|](../knowledge/)|](../|g' \
      -e 's|](../src/)|](../../src/)|g' \
      -e 's|](../FEATURE-STORE\.md)|](FEATURE-STORE.md)|g' \
      -e 's|](../DEPLOY\.md)|](DEPLOY.md)|g' \
      -e 's|](../TREASURY\.md)|](TREASURY.md)|g' \
      -e 's|](../MULTI_AGENT\.md)|](MULTI_AGENT.md)|g' \
      -e 's|](../ONNX\.md)|](ONNX.md)|g' \
      -e 's|](../BANKR\.md)|](BANKR.md)|g' \
      -e 's|](../X-RESEARCH\.md)|](X-RESEARCH.md)|g' \
      -e 's|](../LOCALSONLY\.md)|](LOCALSONLY.md)|g' \
      "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done

echo "Synced sentinel-docs: $OUT"
