/**
 * Static editorial scorecard from TOP100.md (March 15, 2026).
 * Used as fallback for composite/sub-scores and flags when FD snapshot is missing or empty.
 */

export interface EditorialScorecardEntry {
  composite: number;
  growthScore: number;
  valuationScore: number;
  momentumScore: number;
  profitScore: number;
  earningsScore: number;
  balanceSheetScore: number;
  insiderScore: number;
  flags: string[];
}

function flags(flagsStr: string): string[] {
  if (!flagsStr || flagsStr === "-") return [];
  return flagsStr.split(", ").filter(Boolean);
}

const ENTRIES: Array<[string, EditorialScorecardEntry]> = [
  [
    "SNDK",
    {
      composite: 81.9,
      growthScore: 92.8,
      valuationScore: 85.6,
      momentumScore: 77.8,
      profitScore: 51.6,
      earningsScore: 97.6,
      balanceSheetScore: 84.6,
      insiderScore: 79.2,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "TSM",
    {
      composite: 71.0,
      growthScore: 61.3,
      valuationScore: 73.4,
      momentumScore: 59.8,
      profitScore: 81,
      earningsScore: 64.4,
      balanceSheetScore: 87.2,
      insiderScore: 94.3,
      flags: flags("high_momentum"),
    },
  ],
  [
    "EQT",
    {
      composite: 70.1,
      growthScore: 81.2,
      valuationScore: 78,
      momentumScore: 45.5,
      profitScore: 72.5,
      earningsScore: 94.7,
      balanceSheetScore: 37.7,
      insiderScore: 66,
      flags: flags("insider_selling"),
    },
  ],
  [
    "IONQ",
    {
      composite: 70.0,
      growthScore: 87,
      valuationScore: 62.6,
      momentumScore: 37,
      profitScore: 71.9,
      earningsScore: 97.1,
      balanceSheetScore: 58.6,
      insiderScore: 77.4,
      flags: flags("high_momentum, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "ASML",
    {
      composite: 67.2,
      growthScore: 86,
      valuationScore: 59.1,
      momentumScore: 64.5,
      profitScore: 60.8,
      earningsScore: 41.3,
      balanceSheetScore: 65.2,
      insiderScore: 88.7,
      flags: flags("high_momentum"),
    },
  ],
  [
    "NVDA",
    {
      composite: 66.1,
      growthScore: 76.4,
      valuationScore: 46.2,
      momentumScore: 46,
      profitScore: 88.9,
      earningsScore: 90.3,
      balanceSheetScore: 80.2,
      insiderScore: 9.4,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "MU",
    {
      composite: 64.7,
      growthScore: 67.3,
      valuationScore: 47.5,
      momentumScore: 73.1,
      profitScore: 71.7,
      earningsScore: 91.6,
      balanceSheetScore: 62,
      insiderScore: 26.4,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "META",
    {
      composite: 64.5,
      growthScore: 75.4,
      valuationScore: 68,
      momentumScore: 33.1,
      profitScore: 61.8,
      earningsScore: 94.6,
      balanceSheetScore: 75.4,
      insiderScore: 17,
      flags: flags("insider_selling"),
    },
  ],
  [
    "GEV",
    {
      composite: 61.9,
      growthScore: 85.4,
      valuationScore: 51.6,
      momentumScore: 60.3,
      profitScore: 35.3,
      earningsScore: 92.2,
      balanceSheetScore: 43.1,
      insiderScore: 47.2,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "EME",
    {
      composite: 59.6,
      growthScore: 63.2,
      valuationScore: 74.7,
      momentumScore: 55,
      profitScore: 22.9,
      earningsScore: 81,
      balanceSheetScore: 60.9,
      insiderScore: 60.4,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "GOOGL",
    {
      composite: 58.7,
      growthScore: 44.6,
      valuationScore: 71.5,
      momentumScore: 47.9,
      profitScore: 72.5,
      earningsScore: 77.3,
      balanceSheetScore: 74.6,
      insiderScore: 0,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "ASTS",
    {
      composite: 58.0,
      growthScore: 76.9,
      valuationScore: 69.3,
      momentumScore: 77.8,
      profitScore: 9.8,
      earningsScore: 70.7,
      balanceSheetScore: 38.1,
      insiderScore: 18.9,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "LITE",
    {
      composite: 57.9,
      growthScore: 96.1,
      valuationScore: 23.9,
      momentumScore: 84.9,
      profitScore: 30.7,
      earningsScore: 73,
      balanceSheetScore: 22.5,
      insiderScore: 43.4,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "ANET",
    {
      composite: 57.2,
      growthScore: 51.7,
      valuationScore: 35.7,
      momentumScore: 59.7,
      profitScore: 75.5,
      earningsScore: 79.1,
      balanceSheetScore: 66.3,
      insiderScore: 45.3,
      flags: flags("high_momentum, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "MSFT",
    {
      composite: 56.5,
      growthScore: 51.6,
      valuationScore: 50.3,
      momentumScore: 30.3,
      profitScore: 83.7,
      earningsScore: 78.5,
      balanceSheetScore: 57.1,
      insiderScore: 58.5,
      flags: flags("insider_selling"),
    },
  ],
  [
    "PLTR",
    {
      composite: 56.4,
      growthScore: 74,
      valuationScore: 11,
      momentumScore: 44.2,
      profitScore: 87.1,
      earningsScore: 87.9,
      balanceSheetScore: 71.2,
      insiderScore: 1.9,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "STX",
    {
      composite: 55.7,
      growthScore: 57.5,
      valuationScore: 52.3,
      momentumScore: 76.9,
      profitScore: 44.4,
      earningsScore: 67,
      balanceSheetScore: 35.4,
      insiderScore: 49.1,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "VRT",
    {
      composite: 54.7,
      growthScore: 62.3,
      valuationScore: 48.1,
      momentumScore: 70.7,
      profitScore: 35.9,
      earningsScore: 53.2,
      balanceSheetScore: 53.9,
      insiderScore: 54.7,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "NVO",
    {
      composite: 54.3,
      growthScore: 48.3,
      valuationScore: 57.3,
      momentumScore: 31.1,
      profitScore: 81.7,
      earningsScore: 78.6,
      balanceSheetScore: 13.8,
      insiderScore: 92.5,
      flags: flags("drawdown_40pct"),
    },
  ],
  [
    "CDNS",
    {
      composite: 53.9,
      growthScore: 70,
      valuationScore: 31.5,
      momentumScore: 34.1,
      profitScore: 64.2,
      earningsScore: 58.4,
      balanceSheetScore: 63.9,
      insiderScore: 62.3,
      flags: flags("pe_above_50_low_growth, insider_selling"),
    },
  ],
  [
    "AMZN",
    {
      composite: 53.8,
      growthScore: 63.4,
      valuationScore: 72.4,
      momentumScore: 34.1,
      profitScore: 31.1,
      earningsScore: 55.2,
      balanceSheetScore: 53.5,
      insiderScore: 56.6,
      flags: flags("insider_selling"),
    },
  ],
  [
    "CRWD",
    {
      composite: 53.1,
      growthScore: 71.9,
      valuationScore: 41.8,
      momentumScore: 41.2,
      profitScore: 33.3,
      earningsScore: 84.4,
      balanceSheetScore: 45.4,
      insiderScore: 52.8,
      flags: flags("insider_selling"),
    },
  ],
  [
    "KLAC",
    {
      composite: 52.7,
      growthScore: 37.6,
      valuationScore: 43.2,
      momentumScore: 67.3,
      profitScore: 70.6,
      earningsScore: 39.5,
      balanceSheetScore: 64.4,
      insiderScore: 71.7,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "ISRG",
    {
      composite: 51.7,
      growthScore: 58.1,
      valuationScore: 21.5,
      momentumScore: 36.8,
      profitScore: 60.8,
      earningsScore: 78.1,
      balanceSheetScore: 86,
      insiderScore: 37.7,
      flags: flags("pe_above_50_low_growth, insider_selling"),
    },
  ],
  [
    "AVGO",
    {
      composite: 51.3,
      growthScore: 47.9,
      valuationScore: 44.5,
      momentumScore: 50.7,
      profitScore: 79.1,
      earningsScore: 45.4,
      balanceSheetScore: 51.6,
      insiderScore: 24.5,
      flags: flags(
        "pe_above_50_low_growth, high_momentum, drawdown_40pct, insider_selling",
      ),
    },
  ],
  [
    "REGN",
    {
      composite: 51.3,
      growthScore: 17.9,
      valuationScore: 76.6,
      momentumScore: 57.7,
      profitScore: 66.7,
      earningsScore: 34.2,
      balanceSheetScore: 89.1,
      insiderScore: 11.3,
      flags: flags("insider_selling"),
    },
  ],
  [
    "AMAT",
    {
      composite: 50.8,
      growthScore: 32.8,
      valuationScore: 42.7,
      momentumScore: 74,
      profitScore: 54.9,
      earningsScore: 66,
      balanceSheetScore: 65.3,
      insiderScore: 32.1,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "CCJ",
    {
      composite: 50.7,
      growthScore: 50,
      valuationScore: 16,
      momentumScore: 69.3,
      profitScore: 50,
      earningsScore: 50,
      balanceSheetScore: 75.5,
      insiderScore: 90.6,
      flags: flags("pe_above_50_low_growth, high_momentum"),
    },
  ],
  [
    "CRCL",
    {
      composite: 49.5,
      growthScore: 43.9,
      valuationScore: 60.6,
      momentumScore: 70.4,
      profitScore: 35.9,
      earningsScore: 62.2,
      balanceSheetScore: 22.3,
      insiderScore: 39.6,
      flags: flags("drawdown_40pct, insider_selling"),
    },
  ],
  [
    "LRCX",
    {
      composite: 49.1,
      growthScore: 28.9,
      valuationScore: 36.5,
      momentumScore: 89.6,
      profitScore: 57.5,
      earningsScore: 62.1,
      balanceSheetScore: 51.8,
      insiderScore: 22.6,
      flags: flags("high_momentum, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "LLY",
    {
      composite: 48.2,
      growthScore: 50.8,
      valuationScore: 25.7,
      momentumScore: 41.6,
      profitScore: 83,
      earningsScore: 83.5,
      balanceSheetScore: 31.7,
      insiderScore: 3.8,
      flags: flags("insider_selling"),
    },
  ],
  [
    "CLS",
    {
      composite: 48.1,
      growthScore: 57.6,
      valuationScore: 57.7,
      momentumScore: 52.8,
      profitScore: 14.4,
      earningsScore: 71.7,
      balanceSheetScore: 45.4,
      insiderScore: 7.5,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "DDOG",
    {
      composite: 46.6,
      growthScore: 71,
      valuationScore: 16.8,
      momentumScore: 40.7,
      profitScore: 37.3,
      earningsScore: 59.4,
      balanceSheetScore: 62,
      insiderScore: 34,
      flags: flags("pe_above_50_low_growth, insider_selling"),
    },
  ],
  [
    "RTX",
    {
      composite: 46.1,
      growthScore: 38.3,
      valuationScore: 70.6,
      momentumScore: 54,
      profitScore: 17.6,
      earningsScore: 30.5,
      balanceSheetScore: 36.9,
      insiderScore: 98.1,
      flags: flags("high_momentum"),
    },
  ],
  [
    "GE",
    {
      composite: 46.0,
      growthScore: 47.7,
      valuationScore: 45.2,
      momentumScore: 49.3,
      profitScore: 39.2,
      earningsScore: 64.3,
      balanceSheetScore: 32.4,
      insiderScore: 41.5,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "ETN",
    {
      composite: 45.4,
      growthScore: 44.3,
      valuationScore: 58,
      momentumScore: 37.4,
      profitScore: 34.6,
      earningsScore: 16.9,
      balanceSheetScore: 53.8,
      insiderScore: 96.2,
      flags: flags("-"),
    },
  ],
  [
    "ARM",
    {
      composite: 45.3,
      growthScore: 33.5,
      valuationScore: 32.6,
      momentumScore: 33.1,
      profitScore: 62.7,
      earningsScore: 50.3,
      balanceSheetScore: 66.8,
      insiderScore: 86.8,
      flags: flags("pe_above_50_low_growth"),
    },
  ],
  [
    "MRVL",
    {
      composite: 45.2,
      growthScore: 19.9,
      valuationScore: 64.6,
      momentumScore: 56.3,
      profitScore: 43.8,
      earningsScore: 39.2,
      balanceSheetScore: 48.8,
      insiderScore: 69.8,
      flags: flags("insider_selling"),
    },
  ],
  [
    "PWR",
    {
      composite: 44.5,
      growthScore: 41,
      valuationScore: 65.5,
      momentumScore: 60.7,
      profitScore: 10.5,
      earningsScore: 37.1,
      balanceSheetScore: 42.4,
      insiderScore: 50.9,
      flags: flags("pe_above_50_low_growth, high_momentum, insider_selling"),
    },
  ],
  [
    "FLEX",
    {
      composite: 43.0,
      growthScore: 41.9,
      valuationScore: 55.1,
      momentumScore: 45.1,
      profitScore: 9,
      earningsScore: 63.6,
      balanceSheetScore: 32.2,
      insiderScore: 75.5,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "ORCL",
    {
      composite: 42.2,
      growthScore: 30.5,
      valuationScore: 55.1,
      momentumScore: 28.9,
      profitScore: 56.2,
      earningsScore: 42.1,
      balanceSheetScore: 15.5,
      insiderScore: 100,
      flags: flags("drawdown_40pct"),
    },
  ],
  [
    "BWXT",
    {
      composite: 42.1,
      growthScore: 30.8,
      valuationScore: 32.3,
      momentumScore: 53.6,
      profitScore: 33.1,
      earningsScore: 68.3,
      balanceSheetScore: 39.3,
      insiderScore: 83,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "PANW",
    {
      composite: 42.1,
      growthScore: 47.3,
      valuationScore: 19.6,
      momentumScore: 39.7,
      profitScore: 52.9,
      earningsScore: 76.6,
      balanceSheetScore: 45.4,
      insiderScore: 5.7,
      flags: flags("pe_above_50_low_growth, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "NOW",
    {
      composite: 41.3,
      growthScore: 42.5,
      valuationScore: 47.9,
      momentumScore: 25,
      profitScore: 39,
      earningsScore: 40.1,
      balanceSheetScore: 43.2,
      insiderScore: 64.2,
      flags: flags("pe_above_50_low_growth, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "NEE",
    {
      composite: 40.9,
      growthScore: 11.1,
      valuationScore: 64.1,
      momentumScore: 45.9,
      profitScore: 58.8,
      earningsScore: 40.4,
      balanceSheetScore: 13.5,
      insiderScore: 84.9,
      flags: flags("insider_selling"),
    },
  ],
  [
    "SNPS",
    {
      composite: 40.7,
      growthScore: 30,
      valuationScore: 50.3,
      momentumScore: 39.2,
      profitScore: 30.7,
      earningsScore: 38.2,
      balanceSheetScore: 51.6,
      insiderScore: 73.6,
      flags: flags("pe_above_50_low_growth, insider_selling"),
    },
  ],
  [
    "HOOD",
    {
      composite: 40.0,
      growthScore: 43.3,
      valuationScore: 18,
      momentumScore: 41.4,
      profitScore: 84.2,
      earningsScore: 39.5,
      balanceSheetScore: 17,
      insiderScore: 20.8,
      flags: flags(
        "pe_above_50_low_growth, high_momentum, drawdown_40pct, insider_selling",
      ),
    },
  ],
  [
    "WDAY",
    {
      composite: 40.0,
      growthScore: 36.7,
      valuationScore: 58.4,
      momentumScore: 25,
      profitScore: 37.9,
      earningsScore: 35.2,
      balanceSheetScore: 54,
      insiderScore: 15.1,
      flags: flags("pe_above_50_low_growth, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "OKLO",
    {
      composite: 39.0,
      growthScore: 28.2,
      valuationScore: 38.7,
      momentumScore: 47.1,
      profitScore: 50,
      earningsScore: 11.5,
      balanceSheetScore: 71.2,
      insiderScore: 28.3,
      flags: flags("high_momentum, drawdown_40pct, insider_selling"),
    },
  ],
  [
    "NET",
    {
      composite: 35.4,
      growthScore: 31.1,
      valuationScore: 38,
      momentumScore: 50.8,
      profitScore: 26.1,
      earningsScore: 41.7,
      balanceSheetScore: 25.7,
      insiderScore: 35.8,
      flags: flags("high_momentum, insider_selling"),
    },
  ],
  [
    "COIN",
    {
      composite: 33.2,
      growthScore: 25.5,
      valuationScore: 54,
      momentumScore: 31.3,
      profitScore: 33.3,
      earningsScore: 2,
      balanceSheetScore: 54.7,
      insiderScore: 13.2,
      flags: flags("drawdown_40pct, insider_selling"),
    },
  ],
  [
    "VST",
    {
      composite: 32.6,
      growthScore: 11.5,
      valuationScore: 64.9,
      momentumScore: 40.8,
      profitScore: 26.8,
      earningsScore: 2.9,
      balanceSheetScore: 22.5,
      insiderScore: 81.1,
      flags: flags("pe_above_50_low_growth, insider_selling"),
    },
  ],
  [
    "ZS",
    {
      composite: 30.3,
      growthScore: 11.7,
      valuationScore: 47.1,
      momentumScore: 25,
      profitScore: 29.4,
      earningsScore: 31.8,
      balanceSheetScore: 32,
      insiderScore: 67.9,
      flags: flags("drawdown_40pct, insider_selling"),
    },
  ],
  [
    "CEG",
    {
      composite: 28.5,
      growthScore: 7.2,
      valuationScore: 49,
      momentumScore: 39.8,
      profitScore: 26.6,
      earningsScore: 28.9,
      balanceSheetScore: 25.7,
      insiderScore: 30.2,
      flags: flags("insider_selling"),
    },
  ],
];

export const EDITORIAL_SCORECARD = new Map<string, EditorialScorecardEntry>(
  ENTRIES,
);

export function getEditorialScorecard(
  ticker: string,
): EditorialScorecardEntry | undefined {
  return EDITORIAL_SCORECARD.get(ticker.toUpperCase());
}
